global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # If you add exporters for workers, list them here:
  #- job_name: 'citus-workers'
  #  static_configs:
  #    - targets:
  #        - 'worker1-exporter:9187'
  #        - 'worker2-exporter:9187'